// RootLayout.js

import React from 'react';
import { Toaster } from 'react-hot-toast';
import { Layout } from '../components';
import './globals.css';
import { Inter } from 'next/font/google';
import { StateContext } from '../context/StateContext';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add your meta tags, stylesheets, and other head elements here */}
      </head>
      <body className={inter.className}>
        <StateContext>
          <Layout>
            <Toaster/>
            {children}
          </Layout>
        </StateContext>
      </body>
    </html>
  );
}
